[package]
name = "track-time"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["cargo", "derive"] }
rusqlite = "0.28.0"
uuid = { version = "1.3.0", features = ["v4"] }
